---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - command: /sbin/init
    image: 'ubuntu:16.04'
    name: ubuntu-16.04
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: ansible
verifier:
  name: testinfra
